@domain = http://localhost:4000
@AccessToken = {{loginToken.response.body.$.access_token}}
###
# 회원가입
# 관리자 회원
POST {{domain}}/user/signup
Content-Type: application/json

{
	"email":"admin@gmail.com",
	"password":"test_pw",
  	"role":1,
	"name" : "이름"
}

###
# 회원가입
# 일반 회원
POST {{domain}}/user/signup
Content-Type: application/json

{
	"email":"test1@gmail.com",
	"password":"test_pw",
  	"role":0,
	"name" : "dlfma"
}

###
# 로그인
# 이 요청은 사용자 로그인을 처리합니다.
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
	"email":"test1@test.com",
	"password":"1234"
}

###
# 로그아웃
# 이 요청은 사용자의 로그아웃을 처리합니다.
POST {{domain}}/user/logout
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 사용자 정보 조회
# 이 요청은 현재 로그인된 사용자의 정보를 조회합니다. (인증 토큰 필요)
GET {{domain}}/user/profile
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

### 액세스 토큰 발급
GET {{domain}}/auth
Authorization: Bearer {{AccessToken}}

##### BOARD
###
# 보드 저장
POST {{domain}}/board
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"title":"test2"
}

###
# 보드 목록 조회
GET {{domain}}/board
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 보드 상세 조회
GET {{domain}}/board/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 보드 정보 수정
PATCH {{domain}}/board/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"title":"test11"
}

###
# 보드 정보 삭제
DELETE {{domain}}/board/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

##### COLUMN
@board_id = 2
###
# 칼럼 저장
POST {{domain}}/board-column/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"title":"column7"
}

###
# 칼럼 목록 조회
GET {{domain}}/board-column/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 칼럼 상세 조회
GET {{domain}}/board-column/1/3
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 칼럼 정보 수정
PATCH {{domain}}/board-column/2/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"title":"test111"
}

###
# 칼럼 정보 삭제
DELETE {{domain}}/board-column/1/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

##### BOARD_MEMBER
###
# 보드 멤버 저장
POST {{domain}}/board-member/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"user_id": 2,
	"role": 2
}

###
# 보드 멤버 목록 조회
GET {{domain}}/board-member/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 보드 멤버 상세 조회
GET {{domain}}/board-member/1/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 보드 멤버 수정
PATCH {{domain}}/board-member/1/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
	"role": 1
}

###
# 보드 멤버 삭제
DELETE {{domain}}/board-member/1/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json